version: "3"

volumes:
  link_shortener_local_postgres_data: {}
  link_shortener_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    image: link_shortener_local_django
    container_name: link_shortener_local_django
    platform: linux/x86_64
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./docker/production/postgres/Dockerfile
    image: link_shortener_production_postgres
    container_name: link_shortener_local_postgres
    volumes:
      - link_shortener_local_postgres_data:/var/lib/postgresql/data:Z
      - link_shortener_local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres
