# Generated by Django 3.2.15 on 2022-08-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full", models.TextField()),
                ("short", models.CharField(db_index=True, max_length=50, unique=True)),
            ],
        ),
    ]
