# Generated by Django 3.2.15 on 2022-08-24 00:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='full',
            field=models.TextField(validators=[django.core.validators.URLValidator()]),
        ),
    ]
